# Artificial Neural Network

## Importing the libraries

In [3]:
import numpy as np
import pandas as pd 
import tensorflow as tf
tf.__version__

'2.12.0'

## Part 1 - Data Preprocessing

## Importing the dataset

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


## Encoding categorical data

## Label Encoding the "Gender" column

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


## One Hot Encoding the "Geography" column

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


## Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=0)

## Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

## Initializing the ANN

In [9]:
ann = tf.keras.models.Sequential()

## Adding the input layer and the first hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## Adding the second hidden layer

In [11]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## Adding the output layer

In [12]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

## Compiling the ANN

In [13]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

## Training the ANN on the Training set

In [14]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.5543 - accuracy: 0.7955
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4717 - accuracy: 0.7962
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4456 - accuracy: 0.8055
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4353 - accuracy: 0.8089
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4297 - accuracy: 0.8115
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4258 - accuracy: 0.8146
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4220 - accuracy: 0.8176
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4191 - accuracy: 0.8199
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4159 - accuracy: 0.8230
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4131 - accura

## Part 4 - Making the predictions and evaluating the model

## Predicting the result of a single observation

In [15]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > .5)

1/1 [==============================] - 0s 201ms/step
[[False]]


## Predicting the Test set results

In [16]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > .5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

63/63 [==============================] - 0s 3ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Making the Confusion Matrix

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1540   55]
 [ 214  191]]


0.8655